name = "SyntheticSMLMData"
uuid = "a4e69437-5a00-4f13-9219-da20d496a7e3"
authors = ["Hossein Zarei Oshtolagh <hzoshtolagh@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
